 workflows: # Define a Workflow running the build job, then the deploy job
   version: 2
   build-deploy:
     jobs:
       - build
       - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded asd
           - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only: master # Only deploys when the commit is on the Master branch

 jobs:
   build:
     working_directory: ~/repo
     docker:
      - image: circleci/openjdk:8-jdk-browsers # <2>
     environment:
      JVM_OPTS: -Xmx3200m  # <3>
      TERM: dumb
     steps: # <4>
      - checkout  # <5>
      - restore_cache: # <6>
                key: grailsapp-{{ checksum "/root/app/build.gradle" }}-{{ checksum "/root/gradle.properties" }}-{{ arch}}
      - run: sudo chmod +x gradlew
      - run: ./gradlew --console=plain testClasses  # <7>
      - run: ./gradlew --console=plain integrationTestClasses  # <8>
      - save_cache: # <9>
                paths:
                  - ~/.gradle
                key: grailsapp-{{ checksum "/root/app/build.gradle" }}-{{ checksum "/root/gradle.properties" }}-{{ arch}}
      - run: ./gradlew bootWar  # <10>
      - store_artifacts: # <11>
          path: build/libs
          destination: libs
      - store_test_results: # <12>
          path: build/test-results

   deploy:
     working_directory: ~/repo
     docker:
      - image: circleci/openjdk:8-jdk-browsers # <2>
     environment:
      JVM_OPTS: -Xmx3200m  # <3>
      TERM: dumb
     steps: # <4>
      - checkout  # <5>
      - restore_cache: # <6>
                key: grailsapp-{{ checksum "/root/app/build.gradle" }}-{{ checksum "/root/gradle.properties" }}
      - run: sudo chmod +x gradlew
      - save_cache: # <9>
                paths:
                  - ~/.gradle
                key: grailsapp-{{ checksum "/root/app/build.gradle" }}-{{ checksum "/root/gradle.properties" }}
      - run: ./gradlew bootWar  # <10>
      - run: # Upload War
           name: Upload war
           command: curl --upload-file /home/circleci/repo/build/libs/repo-0.1.war http://186.108.241.244:8080/manager/text/deploy?path=/my-app --user tomcat:tomcat
