 workflows: # Define a Workflow running the build job, then the deploy job
   version: 2
   build-and-manual-deploy:
     jobs:
       - build
       - hold: # <<< A job that will require manual approval in the CircleCI web application.
           type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
           requires: # We only run the "hold" job when test2 has succeeded
             - build
       - deploy:
           requires:
             - hold
           filters:
             branches:
               only: master # Only deploys when the commit is on the Master branch

 jobs:
   build:
     working_directory: ~/repo
     docker:
      - image: circleci/openjdk:11-jdk-browsers # <2>
     environment:
      JVM_OPTS: -Xmx3200m  # <3>
      TERM: dumb
     steps: # <4>
      - checkout  # <5>
      - restore_cache: # <6>
                key: grailsapp-{{ checksum "root/app/build.gradle" }}-{{ checksum "root/gradle.properties" }}
      - run:
          working_directory: ~/repo/root
          name: change gradle permissions
          command: chmod +x gradlew
      - run:
          working_directory: ~/repo/root
          name: test classes
          command: ./gradlew --console=plain testClasses
      - save_cache: # <9>
                paths:
                  - ~/.gradle
                key: grailsapp-{{ checksum "root/app/build.gradle" }}-{{ checksum "root/gradle.properties" }}
      - run:
          working_directory: ~/repo/root
          name: build war
          command: ./gradlew bootWar
      - store_artifacts: # <11>
          path: root/app/build/libs
          destination: libs
      - store_test_results: # <12>
          path: build/test-results
   deploy:
     working_directory: ~/repo
     docker:
      - image: circleci/openjdk:11-jdk-browsers # <2>
     environment:
      JVM_OPTS: -Xmx3200m  # <3>
      TERM: dumb
     steps: # <4>
      - checkout  # <5>
      - restore_cache: # <6>
                key: grailsapp-{{ checksum "root/app/build.gradle" }}-{{ checksum "root/gradle.properties" }}
      - run:
          working_directory: ~/repo/root
          name: change gradle permissions
          command: chmod +x gradlew
      - run:
          working_directory: ~/repo/root
          name: build war
          command: ./gradlew bootWar
      - run: # Upload War
           name: Upload war
           command: curl --upload-file /home/circleci/repo/root/app/build/libs/repo-0.1.war http://186.108.241.244:8080/manager/text/deploy?path=/my-app --user tomcat:tomcat
