 workflows: # Define a Workflow running the build job, then the deploy job
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only: master # Only deploys when the commit is on the Master branch

 jobs:
   build:
     working_directory: ~/repo/root
     docker:
      - image: circleci/openjdk:11-jdk-browsers # <2>
     environment:
      JVM_OPTS: -Xmx3200m  # <3>
      TERM: dumb
     steps: # <4>
      - checkout  # <5>
      - restore_cache: # <6>
                key: grailsapp-{{ checksum "app/build.gradle" }}-{{ checksum "gradle.properties" }}
      - run: chmod +x gradlew
      - run: ./gradlew --console=plain testClasses  # <7>
      - run: ./gradlew --console=plain integrationTestClasses  # <8>
